### ISSUE TITLE
adjust the size of Marker icons

### ISSUE THREAD

**Issue by NailShort** [ilyaliao/cofcat.dev#2]
Hello, I would like to inquire about how to adjust the size of Marker icons.
 Here is my code.
 ``
 <Marker
  v-for="marker in mapPlace"
  :key="marker.id"
  :position="createRandomCoordinate()"
  :icon=" getMarkerIcon(marker)"
  :scaled-size="(40, 55)"
  :size="(40, 55)"
/>
``

**Comment by CofCat456** [comment]
@NailShort Are you asking about the Marker in Voomap?

**Comment by NailShort** [comment]
I found the problem and fixed it. Thanks!

**Comment by CofCat456** [comment]
Happy that you're making use of it !
